# Page settings

baseURL = "https://venturadelmonte.github.io/"
languageCode = "en"
title = "Bonaventura Del Monte, Ph.D."
#theme = "hugo-devresume-theme"
#googleAnalytics = "UA-XXXXXXX-Y"



[params]
    author = "Bonaventura Del Monte"
    description = "Bonaventura Del Monte's personal website"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        title = "Ph.D."
        name = "Bonaventura"
        surname = "Del Monte"
        tagline = "Senior Software Engineer"
        avatar = "mypic.jpg"







    [params.contact]
        enable = true
        location = "Zürich, Switzerland"

        #[[params.contact.list]]
        #icon = "fas fa-phone-square"
        #url = "tel:#"
        #text = "0123 4567 890"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "venturadelmonte [at] gmail [dot] com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "www.yourwebsite.com"







    [params.skills]
        enable = false

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "C++"
        

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "PhD in Computer Science"
        university = "Technische Universität Berlin"
        dates = "2016 - 2022"
        [[params.education.list]]
        degree = "MSc in Computer Science"
        university = "University of Salerno"
        dates = "2013 - 2016"
        [[params.education.list]]
        degree = "BSc in Computer Science"
        university = "University of Salerno"
        dates = "2010 - 2013"








    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "Software Campus"
        body = "Graduate of development program for future IT executives"
        date = "2020"
        link = "https://softwarecampus.de/certificates/17842/"
       








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Italian"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Professional"
        [[params.languages.list]]
        name = "German"
        level = "Intermediate"








    [params.interests]
        enable = false

        [[params.interests.list]]
        name = "Climbing"
        [[params.interests.list]]
        name = "Snowboarding"
        [[params.interests.list]]
        name = "Photography"
        [[params.interests.list]]
        name = "Travelling"








    [params.summary]
        enable = true
        text = """Former Senior Researcher at
[Technical University Berlin](https://www.dima.tu-berlin.de/menue/database_systems_and_information_management_group/?no_cache=1)
collaborating with
[Volker Markl](https://www.dima.tu-berlin.de/menue/mitarbeiter/volker_markl),
[Tilmann Rabl](https://hpi.de/rabl/team/prof-dr-tilmann-rabl.html), and [Steffen Zeuch](http://www.user.tu-berlin.de/zeuchste/).

My research interests deal with designing and 
developing distributed data processing
engines using modern hardware
for scalable, reliable, and efficient stateful stream processing.
I published research papers at different venues including ACM SIGMOD, VLDB, and CIDR.
<!-- {: class="text-justify"} -->

I successfully defended my Ph.D. thesis about "Hardware-conscious techniques for efficient and reliable stateful stream processing" on December 5, 2022. Members of evaluation committee were [Volker Markl](https://www.dima.tu-berlin.de/menue/mitarbeiter/volker_markl),
[Tilmann Rabl](https://hpi.de/rabl/team/prof-dr-tilmann-rabl.html), [Peter Pietzuch](https://www.imperial.ac.uk/people/prp), [Matei Zaharia](https://cs.stanford.edu/people/matei/), and [Stefan Schmid](https://schmiste.github.io/).

Before joining TU Berlin and DFKI,
I received my MSc degree from
[University of Salerno](https://www.unisa.it)
in collaboration with the
[Distributed and Parallel Systems Group, Innsbruck](http://dps.uibk.ac.at/en/index.html)
under supervision of
[Radu Prodan](http://dps.uibk.ac.at/~radu/)
and
[Vittorio Scarano](http://docenti.unisa.it/001717/home).
I developed my Master's thesis while participating to an Erasmus+ program.
"""




    [params.publications]

        enable = true
        [[params.publications.list]]
            title = "Rethinking Stateful Stream Processing with RDMA"
            authors = "Bonaventura Del Monte, Steffen Zeuch, Tilmann Rabl, Volker Markl."
            venue = "SIGMOD'22"
            link = "https://dl.acm.org/doi/abs/10.1145/3514221.3517826"
            slides = "pdfs/SlashSigmod2022.pdf"
            fullvenue = "2022 ACM SIGMOD International Conference on Management of Data, Philadelphia, USA, 2022."
        [[params.publications.list]]
            title = "NebulaStream: Complex Analytics Beyond the Cloud"
            authors = "Steffen Zeuch, Eleni Tzirita Zacharatou, Shuhao Zhang, Xenofon Chatziliadis, Ankit Chaudhary, Bonaventura Del Monte, Dimitrios Giouroukis, Philipp M. Grulich, Ariane Ziehn, Volker Markl."
            venue = "VLDB'20"
            link = "https://www.nebula.stream/paper/zeuch_vliot.pdf"
            slides = ""
            fullvenue = "Very Large Databases Conference, Tokyo, Japan, 2020."
        [[params.publications.list]]
            title = "Rhino: Efficient Management of Very Large Distributed State for Stream Processing Engines"
            authors = "Bonaventura Del Monte, Steffen Zeuch, Tilmann Rabl, Volker Markl."
            venue = "SIGMOD'20"
            link = "https://dl.acm.org/doi/10.1145/3318464.3389723"
            slides = "https://www.slideshare.net/BonaventuraDelMonte/rhino-efficient-management-of-very-large-distributed-state-for-stream-processing-engines"
            fullvenue = "2020 ACM SIGMOD International Conference on Management of Data, Portland, USA, 2020."
        [[params.publications.list]]
            title = "The NebulaStream Platform: Data and Application Management for the Internet of Things"
            authors = "Steffen Zeuch, Ankit Chaudhary, Bonaventura Del Monte, Haralampos Gavriilidis, Dimitrios Giouroukis, Philipp M. Grulich, Sebastian Bress, Jonas Traub, Volker Markl."
            venue = "CIDR'20"
            link = "http://cidrdb.org/cidr2020/papers/p7-zeuch-cidr20.pdf"
            slides = ""
            fullvenue = "Biennial Conference on Innovative Data Systems, Amsterdam, Netherlands, 2020."


    [params.experience]
        enable = false

        [[params.experience.list]]
        title = "Senior Software Engineer"
        dates = "2019 - Present"
        company = "Google"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."
        [[params.experience.list.items]]
        details = "Etiam ultricies nisi vel augue."

        [[params.experience.list]]
        title = "Lead Software Developer"
        dates = "2016 - 2019"
        company = "Apple"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."

        [[params.experience.list]]
        title = "Senior Software Developer"
        dates = "2014 - 2016"
        company = "Dropbox"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Senior Developer"
        dates = "2013 - 2014"
        company = "Uber"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

        [[params.experience.list]]
        title = "Backend Developer"
        dates = "2014 - 2016"
        company = "Amazon"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Frontend Developer"
        dates = "2013 - 2014"
        company = "Startup"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."











    [params.projects]
        enable = false

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."










    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"








    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/VenturaDelMonte"
        title = "VenturaDelMonte"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/bonaventuradelmonte"
        title = "bonaventuradelmonte"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/VenturaDelMonte"
        title = "@VenturaDelMonte"





